<?php include ('element/navbar.php'); ?>
    <div class="main-container">
        <section id="legal-doc" class="space--sm">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h3 class="mb-0">Terms of service</h3>
                        <p>Last update September 19, 2019</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-justify">
                        <p>This agreement (collectively referred to as the "Agreement") between you and Creativechain FDN ("we", "us" or "our"), producer and responsible for Creary establishes your rights of access and use of Creary.net and any other other product or service provided by us ("the service"). If you accept this Agreement and use the Services on behalf of a company, organization, government or other legal entity, you represent and warrant that you are authorized to do so and you have the authority to link to this entity with this Agreement By accessing our Service, you agree that you have read, correctly understood and accepted this Agreement.</p>
                        <p>If we decide to make changes to this Agreement, we will send you a notice of such changes by updating the "Last Update" date above or by posting a notice on Creary.net. The new use of the Service will confirm your acceptance of these changes.</p>
                        <h4>1. Privacy policy</h4>
                        <p>You can consult our Privacy Policy to obtain information on how we collect, use and disclose your information.</p>
                        <h4>2. Eligibility</h4>
                        <p>The Service is not intended to be used by any person under 13 years of age. You must be at least 13 years old to access or use the Service. If you are between 13 and 18 years of age ((or equivalent minimum age in the jurisdiction where you reside), you may only access or use the Service under the supervision of a parent or legal guardian who agrees to be bound by this Agreement.</p>
                        <h4>3. Content</h4>
                        <p>3.1 Content. "Content" means any material, such as audio files, video files, electronic documents, images or text that you publish using Creary services.</p>
                        <p>3.2 Ownership You retain all rights, ownership and responsibility for your Content. We do not claim any ownership rights over your Content.</p>
                        <p>3.3 Access to content. We do not monitor or control what others do with your Content. You are responsible for determining the copyright limitations that may apply to your Content.</p>
                        <h4>4. Research.</h4>
                        <p>4.1 Content filtering. Filtered out. We do not review all content loaded on the Services, but we may use available technologies, providers or processes to filter certain types of illegal content (for example, child pornography) or any other content or inappropriate behavior (for example, activity patterns that indicate spam or identity theft, as well as keywords that indicate that adult content has been published outside of the adult zone limits).</p>
                        <p>4.2 Divulgation. We may access or disclose information about you or your use of the Services or the Software: (a) when required by applicable law (for example, if we receive an official notice, valid citation or a registration warrant); (b) to respond to your requests for assistance service to the user; or (c) when, in our opinion, we consider it necessary to protect the rights, property or personal safety of our users, the public or ourselves, in any seat (contentious or non-contentious).</p>
                        <h4>5. Content that can be published in Creary</h4>
                        <p>In Creary you can post content that you create or possess that does not infringe the rights of others or is illegal or other content that you have permission to upload. This includes content in the public domain, Creative Commons or shared open source in accordance with the specific requirements of the license, and content protected by copyright in which you have legitimate permission from the owner. If you post something that you did not create yourself or that does not belong to you, you agree that you are responsible for any Content that you post; that it will only send Content that it has the right to publish; and that you will fully comply with the licenses of third parties related to the Content you post.</p>
                        <p>Creary is a platform for the distribution of Creative Portfolios and therefore does not allow the use of its platform for criminal, defamatory, degrading, immoral purposes or to promote the illegal consumption of narcotics, weapons or prostitution.</p>
                        <p>Creary has an option to be able to report the content or block all the publications of a user.</p>
                        <p>In the “Crea Blockchain" (Public and Distributed Database Technology where the Creary platform operates) all data is public and can be traced by authorities or third parties. In this way, the Creary development team, like any other person or public entity, will be able to detect users through their public key that they may be infringing or committing a crime related to that published content.</p>
                        <h4>6. IPFS file storage</h4>
                        <p>The Interplanetary File System (IPP) is a protocol and network designed to create a content-addressable peer-to-peer method for storing and sharing hypermedia in a distributed file system. Creary uses this system to store the contents whether they are videos, audio, images or download files. Therefore Creativechain FDN does not store files in servers in a centralized way.</p>
                        <p>For this reason and unlike the metadata embedded in Crea's Blockchain, Creary does not guarantee 100% that content such as videos, audio, images or download files will be hosted on the network in perpetuity. Therefore we recommend that the user and owner of the work keep a copy of the original content to re-register or even be able to prove ownership to third parties using the original hash and the data recorded in the blockchain of Crea. The Creary service can set reasonable technical limits on the file size of each publication that is hosted on the IPFS network.</p>
                        <h4>7. Copyright and limited license</h4>
                        <p>Since the files are stored in the IPFS decentralized file network referred to in this section, we can retain data, text, photographs, images, video, audio, graphics, articles, comments, software, code, scripts and other content provided by us, the Blockchain of Crea or our licensors, which we call "Creary Content". This content is protected by the intellectual property laws in force in Spain and the European Union. Except as set forth in this Agreement and that provided by the authors by adding a distribution license to your work, we do not grant any express or implied right to use the Creary Content.</p>
                        <p>You are granted a limited, non-exclusive, non-transferable and non-sublicensable license to access and use the Service and Creary content for your personal use.</p>
                        <h4>8. Trademark policy</h4>
                        <p>"Creary", the Creary logo and any other product or service name, logos or slogans that may appear on the Service are works owned by Creativechain FDN, under a Creative Commons License CC BY-ND. This license allows redistribution, commercial and non-commercial, as long as the work is not modified and transmitted in its entirety, recognizing its original authorship. The appearance of Creary.net and the Service are protected by copyright with a CC BY-NC license, which allows others to intermingle, adjust and build from their work for non-commercial purposes, and although in their new creations they must recognize Creativechain FDN authorship and can not be used commercially, does not necessarily have to be licensed under the same terms. This is applicable to the elements or concepts of visual design of HTML / CSS, Javascript present in Creary.net.</p>
                        <p>Likewise, the Creary brand is registered in the Intellectual Property Registry of the European Union under registration number 017964531.</p>
                        <p>We encourage third-party dapp developers to build at the top of the block chain of Crea. In case of doubts about the reuse of the elements or visual design concepts of HTML / CSS and Javascript present in Creary.net, please contact us at the email address
                            <a href="mailto:legal@creary.net">legal@creary.net</a>, so that you can resolve any doubts about the reuse and copyright.</p>
                        <p>All other trademarks, registered trademarks, product names and company names or logos mentioned or used in our Service are the property of their respective owners and must be used under the use license indicated for each case. The reference to any product, service, process or other information by name, trademark, manufacturer, supplier or otherwise, does not constitute or imply endorsement, sponsorship or recommendation by us.</p>
                        <h4>9. Users behavior</h4>
                        <p>9.1 Responsible use. The communities of Creary are formed by users who expect a certain level of courtesy and professionalism. You must use the Services in a responsible manner and take care of the good coexistence.</p>
                        <p>9.2 Wrong use. You must not misuse the Services. For example, you should not:</p>
                        <ul>
                            <li><p>(a) sublicense or resell Creary Services</p></li>
                            <li><p>(b) use Creary to build any kind of database outside the community</p></li>
                            <li><p>(c) access or attempt to access the Services by any means other than the Creary interface</p></li>
                            <li><p>(d) circumvent any access restriction with the intention of generating a Sybil attack</p></li>
                            <li><p>(e) share Content or perform behaviors that infringe the intellectual property rights of anyone ("Intellectual property rights" means copyright, moral rights, trademark, commercial image, patent, trade secret, unfair competition, right to privacy, right of publicity and any other property right);</p></li>
                            <li><p>(f) upload or share any Content that is illegal, harmful, threatening, abusive, harmful to others, defamatory, libelous, lewd or profane.</p></li>
                            <li><p>(g) impersonate another natural person or pretend representation of a legal person and / or act on their behalf, make false statements under such conditions or in any other way fake their affiliation or mandate with respect to a natural or legal person;</p></li>
                            <li><p>(h) attempt to deactivate, deteriorate or destroy the Services;</p></li>
                            <li><p>(i) upload, transmit, store or make available any Content or code that contains any virus, malicious code, malware or any component designed to damage or limit the functionality of the Services or the Software or harm other users;</p></li>
                            <li><p>(j) interrupt, interfere with or inhibit any other user from using the Services;</p></li>
                            <li><p>(k) stalk, intimidate, harass others as well as incite others to commit violent acts or harm minors in any way;</p></li>
                            <li><p>(l) deceive other users in order to subtract their private keys as well as try to subtract their tokens through any kind of deception;</p></li>
                            <li><p>(m) make chain letters, junk mail, pyramid schemes, identity theft, spamming or send other unsolicited messages by the platform or its users;</p></li>
                            <li><p>(n) violate the applicable legislation on the minors rights.</p></li>
                        </ul>
                        <h4>10. Assumption of risks and limitations of responsibility.</h4>
                        <p>10.1. You accept and acknowledge that there are risks associated with the use of an Internet-based Crea Blockchain account service that includes, among others, the risk of hardware, software and Internet connection failure, the risk of malicious software introduction and risk. that third parties may obtain unauthorized access to the information stored in your account or associated with it, including, among others, your private keys. You accept and acknowledge that we will not be responsible for failures, interruptions, errors, distortions or communication delays that you may experience while using the Services, whatever the cause.</p>
                        <p>10.2. We don’t make legal or other representation or warranty of any kind, express or implied regarding the content of the Service, the information and functions accessed through the Service, hyperlinks to third-party websites or any violations security associated with the transmission of information through the Service or any website linked by the Service.</p>
                        <p>10.3. We will not be responsible for any loss and will not assume any liability and will not be liable to you for the use of our Services, including, but not limited to, losses, damages or claims arising from: (a) User error such as forgotten passwords, improperly constructed transactions or misused CREA blockchain addresses; (b) Server failure or loss of data; (c) corrupt account files; (d) unauthorized access to applications; (e) Any unauthorized activity of third parties, including, among others, the use of viruses, phishing, brute force or other means of attack against the Service; (f) Regulatory actions in one or more jurisdictions; (g) insufficient interest in Creary.net (h) destabilization of the Blockchain of Crea due to a drastic increase in demand; (i) temporary incoherence of the network; (j) Impossibility to eliminate any information registered in the Blockchain of Crea.</p>
                        <p>10.4.We do not guarantee that the Service or the server that makes it available are free of viruses or errors, that its content is accurate, that it is not interrupted or that defects are corrected. We will not be  responsible for any loss of any kind, for action taken, or taken based on the material or information contained in the Service.</p>
                        <h4>11. Agreement to maintain Creary & Creativechain FDN harmless</h4>
                        <p>11.1. You agree to hold Creativechain FDN harmless. (and to each of our directors, members, employees, delegates and affiliates) of any claim, action, damage, loss, cost or expense, including, among others, reasonable legal fees that arise or are related to:</p>
                        <p>11.1.1. Su uso de, o conducta en relación con, nuestros Servicios;</p>
                        <p>11.1.2. Su incumplimiento de cualquier término en este Acuerdo; o</p>
                        <p>11.1.3. Infracción de cualquier derecho de cualquier otra persona o entidad.</p>
                        <h4>12. No responsibility for services and third-party content</h4>
                        <p>12.1.By using our Services, you can view the content or use services provided by third parties, including links to web pages and services of those parties ("Third party content"). We do not control, endorse or adopt any Third Party Content and we will not be responsible for the Content of third parties, including, among others, materials that may be misleading, incomplete, erroneous, offensive, indecent or objectionable in accordance with applicable law. In addition, your relationships or correspondence with these third parties are exclusively between you and the third parties. We are not responsible for any loss or damage of any kind incurred due to such agreements and you understand that your use of the Third Party Content and your interactions with third parties is at your own risk.</p>
                        <h4>13. Registration in the platform</h4>
                        <p>13.1. You do not need to use a Crea Blockchain account provided by us, and you can create an account independently of the Service. If you wish to use part of the Service, you must create a Crea Blockchain account ("Account"). When you create an account, it is strongly recommended to take the following precautions, because if you do not, you may lose your access and / or control your account: (a) Provide accurate and truthful information; (b) maintain the security of your Account by protecting the password of your Account and access to your computer and your Account; (c) Notify immediately if you discover or suspect any security infringement related to your Account.</p>
                        <p>13.2. You hereby accept and acknowledge that you assume responsibility for all activities that occur in your Account and accept all risks of any authorized or unauthorized access to your Account.</p>
                        <p>13.3. You recognize and understand that cryptography is a field in constant progression. Advances in code deciphering or technical advances, such as the development of high-capacity computing computers or other advanced technologies, may present risks for the Services you use and your Account, which could result in theft or loss of his ownership. By using the Service or accessing the Content of Creary.net, you acknowledge these inherent risks and agree not to be responsible for them.</p>
                        <h4>14. The Creary.net Services</h4>
                        <p>14.1. The Services, among other things, provide software that facilitates the visualization of the transaction data of the "Crea blockchain" without being necessary to access the command line interface Crea Blockchain.</p>
                        <p>14.2. Account and Private Keys. If you agree to create an Account through our Service, we generate a pair of public and private cryptographic keys that are exclusively provided to you and that you fully own; As long as we do not store passwords or private keys for you. We never have access to your private key and we do not keep private keys in your name, and therefore, we do not assume any responsibility for the administration of the private key linked to your account. The private key uniquely matches the name of the account and must be used in connection with the account to authorize the transfer of CREA and Crea Dollar from that account. You are solely responsible for maintaining the security of your private keys. You must keep your access information to the private key secure. Otherwise, you may lose control of CREA, Crea Dollar and Crea Energy associated with your account.</p>
                        <p>14.3. Without password recovery. We do not receive or store in any physical or virtual place the password of your account or the private keys. Your private key is yours and you are solely responsible for its custody. We can not help you with recovering, resetting or recovering your account password. You are the only responsible for remembering your Account password. If you have not securely stored a backup copy of the pair of Accounts and passwords held in your Account, you accept and acknowledge that any CREA, Crea Dollar and Crea Energy that you have associated with that Account will be permanently inaccessible if you do not have your Account Password .</p>
                        <p>14.4.Proceedings. All the Crea Blockchain transactions must be confirmed and registered in Crea Blockchain through the distributed consensus network Crea (a point-to-point network), which is not owned, controlled or operated by Creativechain FDN. The Crea Blockchain is operated by a decentralized network of independent third parties. We have no control over the Crea blockchain  and, therefore, we can not guarantee that the details of the transaction you send through the Services will be confirmed in the Crea blockchain. You acknowledge and agree that the details of the transaction you send through the Services can not be completed, or may be substantially delayed, by the Crea Blockchain. You can use the Services to send these details to the Crea blockchain.</p>
                        <p>14.5. Storage or transmission of CREA, Crea Dollar and Crea Energy. CREA, in any of its forms (CREA, Crea Dollar and Crea Energy) is an intangible digital asset controlled by you. These assets exist only by virtue of the property registry maintained in the Crea chain. The Service does not store, send or receive CREA, Crea Dollar and Crea Energy. Any transfer that may occur in any CREA, Crea Dollar and Crea Energy occurs in the blockchain of Crea and not within the Services. We do not guarantee that the Service will affect the transfer of title or right in any CREA, Crea Dollar and Crea Energy.</p>
                        <p>14.6. Relationship. Nothing in this Agreement is intended to create any association, joint venture, agency between you and us.</p>
                        <p>14.7. Accuracy of information. You represent and warrant that all information you provide through the Services is accurate and complete. You accept and acknowledge that we are not responsible for any errors or omissions you make in connection with a Crea Blockchain transaction initiated through the Services, for example, if you misspell the name of an Account or provide incorrect information. We strongly recommend that you carefully review the details of your transaction before completing it through the Services.</p>
                        <p>14.8. Cancellations or modifications. Once the details of the transaction have been sent to the Crea blockchain through the Services, the Services can not help you cancel or modify the details of your transaction. We have no control over the Crea Blockchain and we do not have the ability to provide any cancellation or modification request.</p>
                        <p>14.9. Taxes. It is your responsibility to determine what taxes, if any, apply to the transactions for which you have sent transaction details through the Services, and it is your responsibility to report and remit the correct tax to the appropriate tax authority. You agree that we are not responsible for determining whether taxes apply to your Crea Blockchain transactions or for collecting, reporting, withholding or remitting taxes arising from any transaction of the Crea blockchain.</p>
                        <p>14.10 Content generated by users. If you access our Services, you may encounter content generated by users that you find offensive or annoying. The only solution in this regard is to stop viewing the content or block the user, without prejudice to the decisions that, by virtue of the content restrictions contained in this agreement, may be taken.</p>
                        <h4>15. Claim of copyright and EUCD.</h4>
                        <p>15.1 We will respond to legitimate requests under the European Union Copyright Directive (EUCD) even if the content is registered in the Blockchain of Crea and it belongs to a decentralized organization and we can not remove the content registered in it. In this sense, we reserve the right to hide access to the content of the user provided through the Service (Creary.net) that we believe may be infringing the copyrights of third parties. If you are aware of the content of the user in the Service that infringes your copyright, you can send a claim for copyright claim in the manner legally required according to the rule of application to the alleged infringement.</p>
                        <p>Disputes over copyright infringement can generate financial liability. Thus, it may be necessary or advisable to consult a lawyer before taking any measure protected by the EUCD directive. The requests will be sent through the contact information below:</p>
                        <p>Delegate of copyright: <a href="mailto:copyright@creary.net" target="_blank">copyright@creary.net</a> (we suggest naming with the mention of copyright or the same avoid the word copyright, to avoid confusion).</p>
                        <p>Please send the following information to our copyright agent:</p>
                        <ul>
                            <li><p>1- The electronic or physical signature of the owner of the copyright or of the person authorized to act on behalf of the owner, as well as the title of representation (contractual or notary);</p></li>
                            <li><p>2- Identification of the work protected by copyright that was allegedly infringed or a representative list of such works; URL or Internet location of materials that are said to infringe or be the object of infringing activity, or information reasonably sufficient to allow us to locate the material.</p></li>
                            <li><p>3- Your name, address, telephone number and email address, accompanied by a statement that (i) you are the copyright owner or authorized to act on behalf of the owner of the copyright and (ii) that you understand that the use of the work in dispute is not authorized by the owner of the copyright, its agent or the law.</p></li>
                        </ul>
                        <p>15.2 Right of opposition to claims of copyright. If you believe that the disputed user content could be removed or incorrectly deleted due to an error or incorrect identification of the material, you can send us notice notifying us of this fact through our copyright delegate (contact information provided above), including in said communication the following:</p>
                        <ul>
                            <li><p>1- Physical or electronic signature of the user or his representative, as well as the title of representation (contractual or notary); Identification of the material that has been removed or to which access and location of the material has been disabled before access to it was eliminated or disabled.</p></li>
                            <li>
                                <p>2- Your name, address and telephone number, as well as a statement from you, which states and justifies that you understand that the material was removed or disabled due to an error or misidentification of the material in dispute.
                                <br>Upon receiving the aforementioned notice of opposition, this will be sent to the complaining party, indicating that we will restore the content reported within a period of 10 working days. If, within such period, the complaining party does not prove that it has taken action to prohibit the use of the disputed content, we will consider restoring the user's content on the site.
                                <br>Our policy is to deny the use of the Service to users that we identify as repeat offenders. We apply this policy at our discretion and in appropriate circumstances, such as when a user has been repeatedly accused of infringing the copyrights or other intellectual property rights of third parties, always allowing the user to object to the decision we make.</p>
                            </li>
                        </ul>
                        <h4>16. Indemnity</h4>
                        <p>All the things you do as well as all the information that you send or post in the Service are at all times your responsibility. It does not make us legally responsible for any of its contents or actions that infringe the law or the rights of a third party or person in any way.</p>
                        <p>Specifically, you agree to keep us, our affiliates, directors, employees, delegates and third-party service providers free from any liability caused by your acts in the use of the service as well as the obligation to indemnify for these damages and losses. You agree to defend them against any claim, cost, damage, loss, expense and any other liability, including attorneys' fees and eventual costs convictions arising out of or related to your access or use of the Service, your violation of this user agreement and / or your violation of the rights of any third party or person.</p>
                        <p>The foundation does not guarantee that the Service and Content of Creary will: (a) be secure or available at any time or place; (b) are accurate, complete, reliable, current or error-free or that any defect or error will be corrected; and (c) are free of viruses or other harmful components. Your use of the Creary Content and Service is at your own risk.</p>
                        <h4>17. Modifications, interruptions or suspensions of the service</h4>
                        <p>We reserve the right to modify or suspend, temporarily or permanently, the Service or any feature or part of the Service, without prior notice. You agree that we will not be responsible for any modification, suspension or interruption of the Service.</p>
                        <h4>18. Jurisdiction and Applicable Law.</h4>
                        <p>The parties, by mutual agreement and expressly renouncing the jurisdiction that may correspond to them, submit to the jurisdiction of the courts and tribunals of the city of Barcelona for issues or incidents that derive from the interpretation, application or validity of this contract, which it is governed by Spanish legislation.</p>
                        <h4>19. Termination</h4>
                        <p>We reserve the right, without prior notice and in our sole discretion, to terminate your license to access and use the Service, which includes, creary.net, and block or prevent your future access and use of the Service we provide.</p>
                        <h4>20. Modifications to the agreement</h4>
                        <p>This Agreement is the entire agreement between you and us regarding the Service. It replaces all prior or contemporaneous agreements between you and us. We can modify this user agreement at any time. If we make changes to this agreement that materially affect your rights, we will send you a notice and keep this edition available as a file on Creary.net. By continuing to use the Services after a change to this agreement, you accept these changes.</p>
                        <h4>21. Miscellaneous.</h4>
                        <p>21.1 Prevalent version in case of diversity of interpretations. In case there are discrepancies between the Spanish and English versions of this agreement, the Spanish version will be prevalent.
                            <br>In the event of any discrepancies between the Spanish and English language versions, the Spanish language version shall be binding.
                        </p>
                        <p>21.2 Notifications. We may notify you by email, postal mail, publications on the Services or by any other legally accepted means.</p>
                        <p>21.3 Prohibition of assignment. You can not assign the Conditions or your rights and obligations under this agreement, in whole or in part, without our written consent, any attempt in this sense being null and void. We may assign our rights to this agreement to a third party without prior consent on your part.</p>
                        <p>21.4 Titles. The titles used in these General Conditions or Additional Conditions are included for convenience and will not be used to interpret meanings or intentions.</p>
                        <p>21.5 Severability. If any provision of these General Conditions or any of the Additional Conditions is considered invalid or unenforceable for any reason, the rest of the General Conditions and the Additional Conditions will continue in full force and effect.</p>
                        <p>21.6 Our failure to exercise or enforce any provision of these Terms shall not constitute a waiver of such provision.</p>
                        <h4>22. Contact information</h4>
                        <p>Notifications to Creativechain FDN should be directed to <a href="mailto:legal@creary.net" target="_blank">legal@creary.net</a></p>
                    </div>
                </div>
            </div>
        </section>
        <script src="/js/common/tags.js"></script>


<?php include ('element/footer.php'); ?>